### ISSUE TITLE
Fix TypeError within Publish feature

### ISSUE THREAD

**Issue by CarolineRinks** [VizerISD/personalhealthcarewallet#20]
Error gets thrown when you reach the "Preview" stage of publishing an asset. We need to fix this before we can publish our own mocked healthcare assets to make progress on issue #6

**Comment by CarolineRinks** [comment]
Temporary quick fix is to remove the preview feature.

**Comment by IanMacDougall** [comment]
Does removing the preview feature allow us to create the asset? If so, I think that should be good enough for right now!

**Comment by CarolineRinks** [comment]
It should, but I haven't tested it
