### ISSUE TITLE
Replace user wallet address with their name

### ISSUE THREAD

**Issue by IanMacDougall** [VizerISD/personalhealthcarewallet#3]
Users do not want to see an abbreviated or full length wallet address; rather, they'd prefer to see their full name show up on their profile page. To make this task easier create a JSON file in the static_data directory that contains a dictionary of our (Ian, Caroline, David) wallet addresses mapped to real/fake names.

**Comment by IanMacDougall** [comment]
@CarolineRinks is this a duplicate issue that you finished in your branch?

**Comment by CarolineRinks** [comment]
Whoops yeah I already did this.

**Comment by CarolineRinks** [comment]
Completed in issue #15
