### ISSUE TITLE
Change all wallet addresses to names

### ISSUE THREAD

**Issue by IanMacDougall** [VizerISD/personalhealthcarewallet#8]
Users do not want to see abbreviated wallet addresses ANYWHERE. Namely the profile page, individual use viz, and transaction history viz. Replace wallet addresses with mocked names of doctors, patients, or hospitals.

**Comment by IanMacDougall** [comment]
<img width="634" alt="Screenshot 2023-04-02 at 2 26 06 PM" src="https://user-images.githubusercontent.com/55931976/229371641-19d21333-f64d-41e3-9573-adab319763dd.png">

Change the two wallet addresses to the user profile name. Remove the unnecessary metadata fields at the bottom of the description window (e.g., DID, **TRANSACTIONAL HISTORY API QUERY**). Remove the extra content after metadata updated sentence.

**Comment by CarolineRinks** [comment]
If possible, instead of hardcoding the Owner, have it link to the user that is currently signed in.
